### ISSUE TITLE
Поддержка vagrant

### ISSUE THREAD

**Issue by gunmetal313** [Tiendil/the-tale#1715]
Делаю поддержку vagrant для разворачивания the-tale.

**Comment by Tiendil** [comment]
Полезное начинание. Если будут какие-либо вопросы — обращайтесь.

**Comment by gunmetal313** [comment]
https://github.com/gunmetal313/the-tale/tree/vagrand_support
Моя ветка

**Comment by Tiendil** [comment]
текущий деплой окружения разработчика  уже делается с помощью Vagrant
