### ISSUE TITLE
Бан в игре "навечно" вызывает OverflowError

### ISSUE THREAD

**Issue by nbadp** [Tiendil/the-tale#1734]
Проявляется как нестабильность в  `the_tale.accounts.tests.test_requests_account.BanRequestsTests.test_success__ban_game` и
`the_tale.accounts.tests.test_requests_account.BanRequestsTests.test_success__ban_total`.

В случае если `'ban_time': random.choice(BAN_TIME.records)` вернет последний элемент (бан на 600+ лет) получим 
```
Traceback (most recent call last):
*начало пропущено*
  File "/home/the-tale/repos/the-tale/the_tale/accounts/prototypes.py", line 159, in ban_game
    self.cmd_update_hero()
  File "/home/the-tale/repos/the-tale/the_tale/accounts/prototypes.py", line 61, in cmd_update_hero
    actual_bills=self.actual_bills)
  File "/home/the-tale/repos/the-tale/the_tale/game/workers/supervisor.py", line 320, in cmd_update_hero_with_account_data
    'ban_end_at': time.mktime(ban_end_at.timetuple()),
OverflowError: mktime argument out of range
```
the-tale/the_tale/game/workers/supervisor.py:
```python
    def cmd_update_hero_with_account_data(self, account_id, is_fast, premium_end_at, active_end_at, ban_end_at, might, actual_bills):
        self.send_cmd('update_hero_with_account_data', {'account_id': account_id,
                                                        'is_fast': is_fast,
                                                        'premium_end_at': time.mktime(premium_end_at.timetuple()),
                                                        'active_end_at': time.mktime(active_end_at.timetuple()),
                                                        'ban_end_at': time.mktime(ban_end_at.timetuple()),
                                                        'might': might,
                                                        'actual_bills': actual_bills})
```
Цитата из [доков](https://docs.python.org/2/library/time.html):
> The functions in this module do not handle dates and times before the epoch or far in the future. The cut-off point in the future is determined by the C library; for Unix, it is typically in 2038.

Эксперименты подтверждают, что забанить можно только до 2038.

Отмечу, что `the_tale.accounts.prototypes.ban_forum()` не вызывает `cmd_update_hero()` и соответственно данной проблемы не имеет.

Еще `cmd_update_hero_with_account_data` есть у воркера в the-tale/the_tale/game/workers/logic.py, но там параметры передаются как есть, без приведения к `time`.

**Comment by Tiendil** [comment]
Судя по описанию проблемы в вики: https://en.wikipedia.org/wiki/Year_2038_problem она свойственна 32-битным системам, в 64-битных порог отодвигается на очень далёкий срок.

На текущий момент игра работает на 64-битной платформе и в будущем переход на 32 бита не планируется, соответственно, это скорее не баг, а ограничение на платформу.

На рабочем сервере вопроизвести проблему не удалось — вечные баны практикуются и ни разу не ломались. Локально удалось воспроизвести только ограничение, свойственное для 64-битных систем, что на работу игры не влияет.

Пока задачу закрываю, но если появится её исправление, не влияющее на основную логику игры, то обязательно приму.
