### ISSUE TITLE
Текст при выполнении задания "покупка артефакта"

### ISSUE THREAD

**Issue by ViacheslavK** [Tiendil/the-tale#1737]
(герой) http://the-tale.org/game/heroes/9738

(запись в дневнике) Велистиан
13:10 22 сухого месяца 121 года
LEXICON_KEY.ACTION_INPLACE_DIARY_BUYING_ARTIFACT_AND_CHANGE: old_artifact=боевой цеп sell_price=317 coins=2483 hero=элис'Аэритасеан artifact=рунный топор

**Comment by Tiendil** [comment]
Спасибо за сообщение.

О проблеме известно, она уже исправлена в рамках работы над новой версией.

Об ошибках лучше сообщать у нас на форуме: http://the-tale.org/forum/subcategories/3 — там сразу скажут, если ошибка уже известна или помогут дополнить описание новой информацией.
