### ISSUE TITLE
Падает тест при применении спутником способности "Безрассудная атака"

### ISSUE THREAD

**Issue by pavetok** [Tiendil/the-tale#1769]
Собственно сам тест

    def test_full_battle__with_companion(self):
        battle_ability = random.choice([ability
                                        for ability in effects.ABILITIES.records
                                        if isinstance(ability.effect, effects.BaseBattleAbility)])

        companion_record = companions_storage.companions.enabled_companions().next()
        companion_record.abilities = container.Container(start=(battle_ability,))

        companion = companions_logic.create_companion(companion_record)
        self.hero.set_companion(companion)

        self.hero.reset_accessors_cache()

        current_time = TimePrototype.get_current_time()

        while len(self.hero.actions.actions_list) != 1:
            self.storage.process_turn()
            current_time.increment_turn()

        self.assertTrue(self.action_idl.leader)

        self.storage._test_save()

Когда в качестве способности выбирается `BattleAbilityRecklessness`, то при попытке изменить здоровье спутника вылетает `def change_health(self, value): raise NotImplementedError()`.

Так и задумано?

**Comment by Tiendil** [comment]
Сам тест падает из-за ошибки в игре, связанной с геймдизайном. Новая способность отнимает здоровье у использующего её, однако у спутников здоровье подчиняется другим правилам, нежели чем у героев и монстров. 

Метод def change_health(self, value): raise NotImplementedError() так и задуман, чтобы отлавливать подобные ошибки.

Решением, по-видимому, будет запретить спутникам использовать данную способность.

**Comment by Tiendil** [comment]
Спасибо за сообщение, это мой существенный недочёт.
