### ISSUE TITLE
Убрать продажу разблокировки предпочтений/гильдий и ввести 2 новые карты

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#1793]
- карта, разблокирующая все предпочтения (легендарная)
- карта, разрешающая создание гильдии (возможно. не легендарная)

**Comment by echurmanov** [comment]
В таких картах нет смыслах. Каждый игр сможет воспользоваться данной картой не больше одного раза в жизни.

**Comment by Tiendil** [comment]
Ненужные карты всегда можно продать на рынке или объединить, сейчас тоже не все карты полезны для игроков.

**Comment by Delargond** [comment]
Карты действительно сомнительные. Ненужные карты и на рынке будут не нужны. 

Первая у игроков  выше 36 уровня будут мертвым грузом лежать, ведь, в отличие от остальных, ее даже если и захочешь использовать, то не получится это сделать.

Деланд.

**Comment by Tiendil** [comment]
Реализовано в рамках gh-2085
