### ISSUE TITLE
Лингвистика: не передаётся переменная в одну из фраз боя

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#1846]
Ангиак бросился в сторону Авендже, но увы, проскочил мимо. Авендже -!damage!♥

http://the-tale.org/forum/threads/4808

**Comment by Delargond** [comment]
Иногда при лечении спутника выдается такая же. Вероятно, когда срабатывает "врачевание".

Северный олень +2♥
Северный олень +!damage!♥

**Comment by Tiendil** [comment]
Исправлено в рамках gh-1900
