### ISSUE TITLE
Ошибки в текстах

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#1906]
- Если город уже имеет специализацию [запятая] и её развитие опустится ниже 50, то город перестанет быть специализированным. 
- на странице о Мастерах в путеводителе лишний подзаголовок "косметические особенности"
- поправить подсказку при наведении на мастера: горожанин − мастер. матерсвто убрать, добавить характеры.

**Comment by Delargond** [comment]
На странице Мастера:

влияние от ближЕнего круга
