### ISSUE TITLE
Мастера: начислено могущество во вред проекту, но нет ни одного героя вредящего Мастеру

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#1944]
![539ff85ee49e4148901a4e953dc02b47](https://cloud.githubusercontent.com/assets/871672/15627660/abdf9d36-24f3-11e6-9a73-a57db6852868.png)

**Comment by Vishoz** [comment]
Положительное влияние тоже начисляется проекту от толпы:
![-](https://cloud.githubusercontent.com/assets/19727312/15774448/fb80271c-2984-11e6-8c95-cdd7f12b990d.png)

![default](https://cloud.githubusercontent.com/assets/19727312/15774440/efc730dc-2984-11e6-9682-707b18801ec6.png)

**Comment by Tiendil** [comment]
Закрыто в пользу gh-1954
