### ISSUE TITLE
Герой может применить на себя способности, которые обычно применяются на врагов

### ISSUE THREAD

**Issue by angru** [Tiendil/the-tale#1965]
Судя по этому [коду](https://github.com/Tiendil/the-tale/blob/rc.0.3.21/the_tale/game/pvp/tests/test_abilities.py#L21) одного из тестов:
```python
        result, account_1_id, bundle_id = register_user('test_user_1', 'test_user_1@test.com', '111111')
        result, account_1_id, bundle_id = register_user('test_user_2', 'test_user_2@test.com', '111111')

        self.hero = heroes_logic.load_hero(account_id=account_1_id)
        self.enemy = heroes_logic.load_hero(account_id=account_1_id)
```

Есть вероятность, что герой может применить на себя способности, которые обычно применяются на врагов

**Comment by Tiendil** [comment]
Это сугубо ошибка в тесте. Функциям, отвечающим за бой, нет необходимости проверять для кого их вызывают, поскольку это потенциально ограничивает возможность их использования, но не несёт никакой пользы.
