### ISSUE TITLE
Выбирать противника ради победы в проекте не выгодно

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#2015]
От вреда противнику уменьшается его влияние и, соответственно, профит от проекта.

Не факт, что это плохо, но необходимо рассмотреть последствия.

**Comment by Vishoz** [comment]
Не выгодно - это факт. 
Противника имеет смысл сейчас использовать только для того, чтобы разово опустить влияние мастеру. Постоянное использование оттягивает профит с соратника.
Бесчестным невыгодно быть еще больше.

**Comment by Tiendil** [comment]
Профит с сортаника оттягивается слабо, вряд ли это может заметно влиять на что-то. Соответственно, малый профит с малого влияния лучше чем отсутствие профита.

Частично изменил правила выполнения проектов в gh-2047
