### ISSUE TITLE
Политика: переименовать в Историю

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#2026]
Законы переименовать в события

**Comment by Nevardas** [comment]
Аве.
Обсудив переименование с редакцией, мы пришли к выводу, что история не самое лучшее название для раздела. Если уж и менять, то надо что то более логичное и вписывающееся в наши реалии. 
История, это конечно хорошо и события вместе с ней сочетаются хорошо. Но самому механизму нынешней политики не подходит это название. В рамках голосования это название выглядит нелепо. Ну кто голосует за историческое событие? Это глупо

Как-то давно уже обсуждалось это переименование и кто-то выдвинул предложение о книге судьбы. На мой взгляд это самый логичный вариант, который также отражает действие этой механики на мир Сказки. Хранители не боги, слабы, но вместе, в большом количестве, могут воздействовать на судьбы жителей Сказки. Да и выглядит не менее солидно, чем политика.  События в Книгу также вписываются отлично. Да, название и банально, но точно также банальны политика и история. Не помню почему название не понравилось..

Я конечно понимаю, что к летописи отлично подходит именно история. Но одно дело, если бы эту историю писали герои игроков, и другое дело, когда ее пишут Хранители. Это уже не история, а как раз таки влияние на ход судеб. История не будет восприниматься так, как задумано именно по этой причине.

**Comment by Tiendil** [comment]
>Ну кто голосует за историческое событие? Это глупо
Формально, так любое демократическое правительство у нас работает )

Книга судьбы, в общем, нормально подходит. Лучше  истории, согласен.
