### ISSUE TITLE
Спутники: у мёртвых спутников должна действовать часть способностей

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#2070]
- способности на уход от героя
- способности на лечение

**Comment by Vishoz** [comment]
Может быть, если спутник временный, то при смерти у героя подписчика он должен уходить сразу?

**Comment by Delargond** [comment]
По опыту скажу, что даже плохой временный спутник лучше, чем отсутствие спутника вообще. В боях помогает да и кое-какие бонусы при себе имеет. Я считаю, что, если уж решили ввести принцип "спутники подписчиков не умирают", то следует придерживаться его во всех ситуациях. Я за то, чтобы временные спутники не умирали.

**Comment by Tiendil** [comment]
сделал уход умерших временных спутников, лечиться умершие спутники не будут, всё-таки мёртвые
