### ISSUE TITLE
Косяк с игрой и почтой

### ISSUE THREAD

**Issue by RemiZOffAlex** [Tiendil/the-tale#2082]
Ссылка открывается только до надписи: Идёт поиск героя.

На почту написать не могу, т.к. почта support@the-tale.org не работает:
```Это письмо создано автоматически сервером Mail.Ru, отвечать на него не нужно.

К сожалению, Ваше письмо не может быть доставлено одному или нескольким получателям:

  support@the-tale.org
    SMTP error from remote mail server after RCPT TO:<support@the-tale.org>:
    host the-tale.org [88.99.62.196]: 454 4.7.1 <support@the-tale.org>:
    Relay access denied: retry timeout exceeded

Рекомендуем Вам проверить корректность указания адресов получателей.```

**Comment by RemiZOffAlex** [comment]
В меню Игра или http://the-tale.org/game/

**Comment by Tiendil** [comment]
Работу почты исправил.

Со ссылкой проблема где-то на Вашей стороне. Возможные варианты:

- нестандартный браузер;
- отключённый JavaScript;
- какое-нибудь расширение для браузера, ломающее работу скриптов игры.

**Comment by Tiendil** [comment]
Можете написать Ваш ник в игре, начислю могущество.

**Comment by RemiZOffAlex** [comment]
Ник везде одинаковый RemiZOffAlex.

Браузер Chrome, Firefox, Opera (которая на движке Chrome), JavaScript включен, расширения вообще не ставлю. Проблема появилась недавно. Примерно на седьмом уровне моего персонажа (Афанасий).

**Comment by RemiZOffAlex** [comment]
Косяк с игрой нашёл. Косяк был в загрузке скрипта https://cdn.ravenjs.com/3.10.0/raven.min.js с заблокированного домена ravenjs.com (заблокирован был в целях борьбы с рекламой). Может есть смысл указанный скрипт расположить на домене для статики static.the-tale.org?

**Comment by Tiendil** [comment]
Этот домен никак к рекламе не относится. Это мониторинг ошибок.

Файл скорее всего вообще уберу, из-за него скорее всего фкладки с игрой много памяти жрут.
