### ISSUE TITLE
Книга Судеб: убрать обоснование из записей

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#2083]
С появлением обязательных записей в летопись оно потеряло свою важность. Автор закона может написать что угодно в теме форума.

При этому следует сохранить старые обоснования, поскольку в них есть важная информация, как политическая, так и художественная.

Альтернативно, можно вручную перенести необходимые обоснования в 1-ый пост на форуме.

**Comment by Vishoz** [comment]
Может быть таки не надо убирать? Некоторые пишут в обоснование небольшие истории, которые в фольклор не влезают, да и другая полезная информация тоже нередко бывает в обосновании.
А вот убрать обязательность заполнения этого поля - вполне себе вариант.

**Comment by Tiendil** [comment]
Как раз таки плохо, что пишут. Надо дорабатывать фольклор, чтобы в нём писали. А другую полезную информацию можно первым постом на форуме написать.
