### ISSUE TITLE
Карты Судьбы: новые карты

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#2088]
- add gold epic
- add gold legendary
- CHANGE_HABIT_* common
- карта незначительного ремонта здания

**Comment by Vishoz** [comment]
Может быть заодно и карты получения артефактов пофиксишь, чтобы герой чуть выше среднего таки мог их надеть?

**Comment by Tiendil** [comment]
Это известным мне способом не сделать. Если повысить силу получаемых артефактов, то просто сила среднего героя возрастёт и будет то же самое.

**Comment by Vishoz** [comment]
А нельзя их давать как полезность +1 от полезности вещи снаряженной у героя, того же типа, что и артефакт выпавший по карте?

**Comment by Tiendil** [comment]
Для этого уже есть карты заточек. Плюс, такая механика сама по себе рисковая, может сделать дыру в балансе как уже не раз было.

**Comment by Vishoz** [comment]
Заточки все же предназначены для изменения силы уже имеющегося предмета, а не для замены его. А карты, которые призваны давать предмет в большей части случаев этого не делают, Как относится игрокам к тому, что карта говорит одно, а делает другое?
Может быть просто заменять один предмет равным по полезности другим, без всякого переодевания?

**Comment by Tiendil** [comment]
В описании карт написано, что они дают случайный артефакт. 

>Может быть просто заменять один предмет равным по полезности другим, без всякого переодевания?
Это только больше путать будет. Опять таки, целостность дневника нарушается.

**Comment by Vishoz** [comment]
Но не написано, что герой может его не надеть, а тупо продать. А еще точнее, что средний герой будет делать это всегда. Карты для получения денег ведь у нас тоже уже есть )

> Это только больше путать будет. Опять таки, целостность дневника нарушается.
А то, что скрытый потенциал примерно так работает, никого ж не смущает. Так там еще и не написано, что он понизит силу предмета до среднего на уровень героя, тоже зашибись.

**Comment by Tiendil** [comment]
Уточню описание карт.

**Comment by Tiendil** [comment]
реализовано в рамках gh-2085
