### ISSUE TITLE
Города: производство товаров сделать зависимым от площади владений города

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#2090]
Либо только от него либо оставить какую-то долю на уровень экономики.

**Comment by Vishoz** [comment]
То есть экономика поднимает уровень города, а производство растет от даваемой уровнем территории? В общем то будет тоже самое, разве что культура будет опосредованно влиять на производство.

**Comment by Tiendil** [comment]
Это добавит конкуренции соседним городам, станет сложнее иметь рядом крупные поселения.
